Add error handling to RPM build script. Fixes #2571

diff --git a/Code/Mantid/Installers/RPM_Kit/mantid.spec.template b/Code/Mantid/Installers/RPM_Kit/mantid.spec.template
--- a/Code/Mantid/Installers/RPM_Kit/mantid.spec.template
+++ b/Code/Mantid/Installers/RPM_Kit/mantid.spec.template
@@ -77,19 +77,39 @@ sed -i -e "s!MANTIDLIB = .*'!MANTIDLIB = '%{mantidlibdir}'!" SConstruct
 sed -i -e "s!MANTIDPLUGINS = .*'!MANTIDPLUGINS = '%{mantidpluginsdir}'!" SConstruct
 
 %build
+
+handle_errors() {
+   echo "Checking $2 build"
+  if test "$1" -ne "0" ; then
+    echo "Failed"
+    exit ${1}
+  else
+    echo "Passed"
+  fi
+}
+
 cd Code/Mantid/Framework
 sh build.sh rpmbuild=1 skiptest=1 debug=0 -j4
+handle_errors $? "Framework"
+
 cd ../QtPropertyBrowser
 qmake-qt4 QMAKE_CC=gcc44 QMAKE_CXX=g++44 QMAKE_LINK=g++44
 make -j4
+handle_errors $? "QtPropertyBrowser"
+
 cd ../MantidQt
 qmake-qt4 QMAKE_CC=gcc44 QMAKE_CXX=g++44 QMAKE_LINK=g++44
 # Note that the old MantidQt stuff doesn't like being built in parallel
 make
+handle_errors $? "MantidQt"
+
 cd ../MantidPlot
 python release_date.py %{version} SVN_VERSION
+handle_errors $? "release_date"
+
 qmake-qt4 QMAKE_CC=gcc44 QMAKE_CXX=g++44 QMAKE_LINK=g++44
 make -j4
+handle_errors $? "MantidPlot"
 
 %install
 if test "$RPM_BUILD_ROOT" != "/"; then rm -fr "$RPM_BUILD_ROOT"; fi
