Add 'git test review' command. Refs #6708

diff --git a/Code/Tools/Workflow/git/git-test b/Code/Tools/Workflow/git/git-test
--- a/Code/Tools/Workflow/git/git-test
+++ b/Code/Tools/Workflow/git/git-test
@@ -27,8 +27,6 @@ CMD_NAME="test"
 PRODUCTION_BRANCH="master"
 # Config key to store tested branch
 BRANCH_CFG_KEY=mantid.workflow.testbranch
-# Changes filename
-CHANGESFILE_CFG_KEY=mantid.workflow.changesfilename
 
 # Set git to merge silently if everything succceeded
 # See http://git-blame.blogspot.co.uk/2012/02/anticipating-git-1710.html
@@ -41,6 +39,7 @@ export CMDFILE_DIR=$(dirname "$(echo "$0" | sed -e 's@\\@/@g')")
 
 usage() {
     echo "Usage: git ${CMD_NAME} start <branchname>"
+    echo "       git ${CMD_NAME} review"
     echo "       git ${CMD_NAME} pass|fail"
     echo
     echo "In the first form start testing the given <branchname> by checking out ${PRODUCTION_BRANCH} and merging it."
@@ -52,7 +51,12 @@ usage() {
     echo "  git reset --hard origin/${PRODUCTION_BRANCH} (Ensures it looks exactly like origin/${PRODUCTION_BRANCH})"
     echo "  git merge --no-ff <branchname>"
     echo
-    echo "In the second form assume testing has started and indicates success/failure. If they"
+    echo "In the second form assume testing has started and open the compare view on github so that the"
+    echo "changes can be reviewed"
+    echo "Equivalent to:"
+    echo "  git web--browse https://github.com/mantidproject/[REPO]/compare/[branchname]"
+    echo
+    echo "In the third form assume testing has started and indicates success/failure. If they"
     echo "  passed: The commits are pushed to origin --> 'git push origin ${PRODUCTION_BRANCH}'"
     echo "  failed: The merged commits are discarded --> 'git reset --hard origin/${PRODUCTION_BRANCH}'"
     echo
@@ -66,6 +70,7 @@ checkargs() {
     ARG_TEST_BRANCH=""
     START_MODE=0
     RESULT_MODE=0
+    REVIEW_MODE=0
     TEST_PASSED=0
     
     if [ $# -eq 2 ]; then
@@ -76,10 +81,13 @@ checkargs() {
         START_MODE=1
         ARG_TEST_BRANCH=$2
     elif [ $# -eq 1 ]; then
-        RESULT_MODE=1
-        if [ "$1" = "pass" ]; then
+	if [ "$1" = "review" ]; then
+	    REVIEW_MODE=1
+	elif [ "$1" = "pass" ]; then
+            RESULT_MODE=1
             TEST_PASSED=1
         elif [ "$1" = "fail" ]; then
+            RESULT_MODE=1
             TEST_PASSED=0
         else
             usage
@@ -135,29 +143,18 @@ start_testing() {
 	exit 1
     fi
 
-    # Save a file of the changes made on this branch for review and point the tester to 
-    # a prettier version on github
-    # Direct tester to a pretty version of changes on branch on github
-    # If the branchname contains forward slashes they must be converted to semi-colons for github and underscores for the filename
+    # Prompt user to examine changes
     local_testbranch=${remote_testbranch#"origin/"}
-    changes_branch_gh=$(echo ${local_testbranch} | sed -e "s@/@;@g")
-    changes_branch_file=$(echo ${local_testbranch} | sed -e "s@/@_@g")
-    repo_stem=$(git config --get remote.origin.url | sed -e 's@.*github.com[:,/]@@' | sed -e 's@\.git$@@')
-    changes_address="https://github.com/${repo_stem}/compare/${changes_branch_gh}"
-
-    changes_file=${HOME}/${changes_branch_file}"_log"
-    git log HEAD --not origin/master > "${changes_file}"
+    changes_url=$(github_compare_url ${local_testbranch})
 
     # Record what we are testing for later pass/fail
     git config ${BRANCH_CFG_KEY} ${local_testbranch}
-    # Record the file for deletion later
-    git config ${CHANGESFILE_CFG_KEY} ${changes_file}
 
     echo
-    echo "The log of the set of changes made on this branch has been saved to ${changes_file}"
-    echo "For a more readable version please visit ${changes_address}"
+    echo "To review the changes that have been made on this branch run 'git test review'"
+    echo "(This will open the default browser & point it to: ${changes_url} "
     echo
-    echo "The code should be reviewed, built & the feature tested."
+    echo "Along with the review the code should now be built & the feature tested."
     echo "When complete if:"
     echo "  success: run 'git test pass'"
     echo "  failure: run 'git test fail'"
@@ -193,14 +190,19 @@ end_testing() {
         git_halt_on_error reset --hard origin/${PRODUCTION_BRANCH}
     fi
 
-    # Remove the stored keys & changes file
-    changes_file=$(git config ${CHANGESFILE_CFG_KEY})
-    if [ -f "${changes_file}" ]; then
-	rm -f ${changes_file}
-    fi
-    
+    # Clear saved config
     git config --unset ${BRANCH_CFG_KEY}
-    git config --unset ${CHANGESFILE_CFG_KEY}
+
+}
+
+review_changes() {
+    local_testbranch=$(git config ${BRANCH_CFG_KEY})
+    if [ -z ${local_testbranch} ]; then
+        echo "The name of the test branch has not been recorded in the config. Was the testing started with 'git test start'?"
+        exit 1
+    fi
+    changes_url=$(github_compare_url ${local_testbranch})
+    git_halt_on_error web--browse ${changes_url}
 }
 
 main() {
@@ -228,6 +230,8 @@ main() {
 
     if [ $START_MODE -eq 1 ]; then
         start_testing
+    elif [ $REVIEW_MODE -eq 1 ]; then
+	review_changes
     elif [ $RESULT_MODE -eq 1 ]; then
         end_testing
     fi
