Allow git-test to find branch via hint not just full name. Refs #6708

diff --git a/Code/Tools/Workflow/git/git-test b/Code/Tools/Workflow/git/git-test
--- a/Code/Tools/Workflow/git/git-test
+++ b/Code/Tools/Workflow/git/git-test
@@ -103,12 +103,12 @@ start_testing() {
     # Ensure we have everything from the remote
     git_halt_on_error fetch -p
 
-    # Is the name correct
-    remote_branch_exists ${TEST_BRANCH}
-    if [ $? -eq 0 ]; then
-        echo "Cannot find branch \"${TEST_BRANCH}\" on the remote. Is the name correct?"
-        exit 1
-    fi    
+    testbranch=$(find_remote_branch_from_hint $1)
+    if [ -z "$testbranch" ]; then
+	echo "Cannot find branch on remote using hint '$1'."
+	echo "Please use full name (without origin/ prefix)."
+	exit 1
+    fi
 
     startbranch=$(current_branch)
     if [ "${startbranch}" != "${PRODUCTION_BRANCH}" ]; then
@@ -126,7 +126,7 @@ start_testing() {
     git_halt_on_error rebase --preserve-merges origin/${PRODUCTION_BRANCH}
     
     # Merge test branch
-    git_ignore_errors merge --no-ff origin/${TEST_BRANCH}
+    git_ignore_errors merge --no-ff origin/${testbranch}
     if [ $? -gt 0 ]; then
 	echo
 	echo "WARNING: There were conflicts during the merge. If they are trivial please fix them, "
@@ -139,8 +139,8 @@ start_testing() {
     # a prettier version on github
     # Direct tester to a pretty version of changes on branch on github
     # If the branchname contains forward slashes they must be converted to semi-colons for github and underscores for the filename
-    changes_branch_gh=$(echo ${TEST_BRANCH} | sed -e "s@/@;@g")
-    changes_branch_file=$(echo ${TEST_BRANCH} | sed -e "s@/@_@g")
+    changes_branch_gh=$(echo ${testbranch} | sed -e "s@/@;@g")
+    changes_branch_file=$(echo ${testbranch} | sed -e "s@/@_@g")
     repo_stem=$(git config --get remote.origin.url | sed -e 's@.*github.com[:,/]@@' | sed -e 's@\.git$@@')
     changes_address="https://github.com/${repo_stem}/compare/${changes_branch_gh}"
 
@@ -148,7 +148,7 @@ start_testing() {
     git log HEAD --not origin/master > "${changes_file}"
 
     # Record what we are testing for later pass/fail
-    git config ${BRANCH_CFG_KEY} ${TEST_BRANCH}
+    git config ${BRANCH_CFG_KEY} ${testbranch}
     # Record the file for deletion later
     git config ${CHANGESFILE_CFG_KEY} ${changes_file}
 
