Normalise line endings in workflow scripts. Refs #6653
Replacing tabs with spaces and using 4 spaces consistently

diff --git a/Code/Tools/Workflow/git/git-checkbuild b/Code/Tools/Workflow/git/git-checkbuild
--- a/Code/Tools/Workflow/git/git-checkbuild
+++ b/Code/Tools/Workflow/git/git-checkbuild
@@ -56,8 +56,8 @@ usage() {
 checkargs() {
     # Can't use getopt cross-platform
     if [ ! $# -eq 0 ]; then
-	usage
-	exit 1
+        usage
+        exit 1
     fi
 }
 
@@ -70,22 +70,22 @@ main() {
     # Sanity check
     currentbranch=$(current_branch)
     if [ ${currentbranch} = "${BUILD_BRANCH}" ]; then
-	echo "Cannot merge develop into itself. Run this command on a branch that requires checking"
-	exit 1
+        echo "Cannot merge develop into itself. Run this command on a branch that requires checking"
+        exit 1
     fi
 
     if [ ${currentbranch} = "master" ]; then
-	echo "Cannot use this command to merge master->${BUILD_BRANCH}"
-	exit 1
+        echo "Cannot use this command to merge master->${BUILD_BRANCH}"
+        exit 1
     fi
 
     # Run macro
     local_modifications
     if [ $? -eq 1 ]; then
-	echo "You have local modifications. Please either:"
-	echo " 1) Commit the changes and rerun this command. This will include them in the buildserver check."
-	echo " 2) Run 'git stash', rerun this command, then run 'git stash pop'. This will NOT include them in the buildserver check."
-	exit 1
+        echo "You have local modifications. Please either:"
+        echo " 1) Commit the changes and rerun this command. This will include them in the buildserver check."
+        echo " 2) Run 'git stash', rerun this command, then run 'git stash pop'. This will NOT include them in the buildserver check."
+        exit 1
     fi
 
     # Move to develop
diff --git a/Code/Tools/Workflow/git/gitworkflow-helpers b/Code/Tools/Workflow/git/gitworkflow-helpers
--- a/Code/Tools/Workflow/git/gitworkflow-helpers
+++ b/Code/Tools/Workflow/git/gitworkflow-helpers
@@ -27,7 +27,7 @@
 export CMDFILE_DIR=$(dirname "$(echo "$0" | sed -e 's@\\@/@g')")
 
 # Checks if the branch exists locally
-local_branch_exists() { 
+local_branch_exists() {
     git branch --no-color | grep -E "^${1}$"
     retval=$(($? == 1 ? 0 : 1))
     return ${retval}
@@ -41,17 +41,17 @@ remote_branch_exists() {
 }
 
 check_branch_exists() {
-  local_branch_exists ${1}
-  if [ $? -eq 1 ]; then
-      echo "A branch with name '${branchname}' already exists locally. Check ticket reference."
-      exit 1
-  fi
+    local_branch_exists ${1}
+    if [ $? -eq 1 ]; then
+        echo "A branch with name '${branchname}' already exists locally. Check ticket reference."
+        exit 1
+    fi
 
-  remote_branch_exists ${1}
-  if [ $? -eq 1 ]; then
-      echo "A branch with name '${branchname}' already exists on the remote. Check ticket reference."
-      exit 1
-  fi
+    remote_branch_exists ${1}
+    if [ $? -eq 1 ]; then
+        echo "A branch with name '${branchname}' already exists on the remote. Check ticket reference."
+        exit 1
+    fi
 }
 
 # Returns the name of the current branch
@@ -75,14 +75,14 @@ run_git() {
 run_fetch() {
     run_git fetch -p
     if [ $? -gt 0 ]; then
-	echo "Error running fetching. Most likely a network issue. Continuing with current state of ${BASE_BRANCH}."
+        echo "Error running fetching. Most likely a network issue. Continuing with current state of ${BASE_BRANCH}."
     fi
 }
 
 # Checks if we are actually within a git repo
 check_git_repo() {
-  git status | grep "fatal: Not a git repository (or any of the parent directories): .git" > /dev/null
-  if [ $? -eq 0 ]; then
+    git status | grep "fatal: Not a git repository (or any of the parent directories): .git" > /dev/null
+    if [ $? -eq 0 ]; then
         exit 1
-  fi
+    fi
 }
