Tidy up script to use return 1 over fatal

diff --git a/tools/Development/git/git-add-test-data b/tools/Development/git/git-add-test-data
--- a/tools/Development/git/git-add-test-data
+++ b/tools/Development/git/git-add-test-data
@@ -31,7 +31,7 @@ add_test_data() {
   # Compute hash
   hash=$(hash_code $content_file)
   if [ "$hash" = "" ]; then
-    exit 1
+    return 1
   fi
   debug_msg "${INDENT}${HASH_ALG} hash: $hash"
 
@@ -68,11 +68,13 @@ hash_code() {
 # Computes the MD5 checksum of the given file.
 # MD5 code is printed to stdout
 #   @param $1 - Path to the file whose hash is computed
+#   @return 1 failure to create md5sum, 0 on success.
 md5sum() {
   md5cmd="cmake -E md5sum"
   cmake_output=$($md5cmd $1)
   if [ "$cmake_output" = "" ]; then
-    fatal "CMake was unable to create the MD5 Sum"
+    echo "CMake was unable to create the MD5 Sum" 1>&2
+    return 1
   fi
   # CMake output is of form: HASH   filename
   md5=$(echo $cmake_output | awk '{print $1}')
