Improve error reporting. Fixes #875.

diff --git a/Code/RPM_Kit/nightly_build b/Code/RPM_Kit/nightly_build
--- a/Code/RPM_Kit/nightly_build
+++ b/Code/RPM_Kit/nightly_build
@@ -11,11 +11,11 @@ function error_found() {
     local exit_status=${1:-$?}
     echo "Subject: RPM build R$rev FAILED" > $MESS
     echo >> $MESS
-    echo "Nightly RPM build of svn R$rev FAILED with error code $exit_status - see http://vlinux2.isis.cclrc.ac.uk/buildlog/build.log" >> $MESS
+    echo "Nightly RPM build of svn R$rev FAILED with error code $exit_status - see http://vlinux2.isis.cclrc.ac.uk/buildlog/build$revfile.log" >> $MESS
     echo >> $MESS
     echo "** Last few lines of build error **" >> $MESS
     echo >> $MESS
-    tail -20 /var/www/html/buildlog/build.log >> $MESS
+    tail -60 /var/www/html/buildlog/build$revfile.log >> $MESS
     /usr/sbin/sendmail -fRPMBuildServer1@mantidproject.org mantid-buildserver@mantidproject.org < $MESS
     rm -f $MESS
     echo Exiting $0 with $exit_status
@@ -27,16 +27,24 @@ build_base=/home/faa59/mybuilds
 find $build_base -type f -name 'Mantid-*' -exec rm -f {} \;
 cd ~faa59/Mantid
 svn update
-rev=`svnversion -n`
+svn update # do twice in case of network issue
+if ! test -z "$1"; then
+    rev="$1"
+    revfile="_$1"
+else
+    rev=`svnversion -n`
+    rev=`expr match $rev '\([0-9]*\).*'`   # remove trailing M if any
+    revfile=""
+fi
 cd Code/RPM_Kit
-env CC="gcc43" CXX="g++43" MANTID_BUILD_FLAGS="gcc43=1" sh make_rpm.sh -r $rev
+env CC="gcc44" CXX="g++44" MANTID_BUILD_FLAGS="gcc44=1" sh make_rpm.sh -r $rev
 scp $build_base/SRPMS/Mantid-*.*-0.svnR$rev.*.src.rpm isisupdate@shadow:$yum_base/SRPMS
 scp $build_base/RPMS/x86_64/Mantid-*.*-0.svnR$rev.*.x86_64.rpm isisupdate@shadow:$yum_base/x86_64
 scp $build_base/RPMS/x86_64/Mantid-debuginfo-*.*-0.svnR$rev.*.x86_64.rpm isisupdate@shadow:$yum_base/x86_64/debug
 scp Mantid-1.0.tar.gz isisupdate@shadow:/isis/www/mantidproject_download/CurrentBuild
 echo "Subject: RPM build R$rev SUCCEEDED" > $MESS
 echo >> $MESS
-echo "Nightly RPM build of svn R$rev SUCCEEDED - see http://vlinux2.isis.cclrc.ac.uk/buildlog/build.log" >> $MESS
+echo "Nightly RPM build of svn R$rev SUCCEEDED - see http://vlinux2.isis.cclrc.ac.uk/buildlog/build$revfile.log" >> $MESS
 /usr/sbin/sendmail -fRPMBuildServer1@mantidproject.org mantid-buildserver@mantidproject.org < $MESS
 rm -f $MESS
 exit 0
