Try cause a timeout.

diff --git a/buildconfig/Jenkins/buildscript b/buildconfig/Jenkins/buildscript
--- a/buildconfig/Jenkins/buildscript
+++ b/buildconfig/Jenkins/buildscript
@@ -31,7 +31,7 @@ function run_with_xvfb {
     if [ $(command -v xvfb-run) ]; then
         # -e=--error-file. A bug in Xvfb on RHEL7 means --error-file
         # produces an error: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=337703;msg=2
-        xvfb-run -e /dev/stderr --server-args="-core -screen 0 640x480x24 -maxclients 64 -audit 4 -noreset" \
+        xvfb-run -e /dev/stderr --server-args="-core -noreset -screen 0 640x480x24" \
         --server-num=${XVFB_SERVER_NUM} $@
     else
         eval $@
@@ -412,7 +412,7 @@ userprops_file=$userconfig_dir/Mantid.user.properties
 echo MultiThreaded.MaxCores=2 > $userprops_file
 
 if [[ ${DO_UNITTESTS} == true ]]; then
-    run_with_xvfb $CTEST_EXE --repeat-until-fail 500 --no-compress-output -R test_interpreter -j${BUILD_THREADS:?} --output-on-failure
+    run_with_xvfb $CTEST_EXE --repeat-until-fail 50 --no-compress-output -R "test_interpreter.test_interpreter" -j${BUILD_THREADS:?} --output-on-failure
     terminate_xvfb_sessions
 fi
 
