Include exit code and shell output in script pre-commit

diff --git a/buildconfig/Jenkins/pre-commit b/buildconfig/Jenkins/pre-commit
--- a/buildconfig/Jenkins/pre-commit
+++ b/buildconfig/Jenkins/pre-commit
@@ -22,16 +22,19 @@ if [[ $JOB_TYPE == "pull-request" ]]; then
   # If using the snap version (No longer updated but it doesn't use pip on ubuntu, so it's better to be outdated here) run
   # Using the older source
   if [[ ${PRE_COMMIT_VERSION} < "pre-commit 1.22.0" ]]; then
-    $(pre-commit run --origin "${BASE_SHA}" --source "${GIT_SHA}" --show-diff-on-failure --verbose)
+    pre-commit run --origin "${BASE_SHA}" --source "${GIT_SHA}" --show-diff-on-failure --verbose
   else
-    $(pre-commit run --from-ref "${BASE_SHA}" --to-ref "${GIT_SHA}" --show-diff-on-failure --verbose)
+    pre-commit run --from-ref "${BASE_SHA}" --to-ref "${GIT_SHA}" --show-diff-on-failure --verbose
   fi
 elif [[ $JOB_TYPE == "master" ]]; then
-  $(pre-commit run --all-files)
+  pre-commit run --all-files
 else
   echo "JOB_TYPE not set, add a 3rd argument (e.g. master or pull-request)"
   exit 1
 fi
+
+# Define exit code so can be copied later
+EXIT_CODE=$?
 
 # git needs to have a minimal configuration for git commit to work
 if [ "$(git config user.name)" == "" ]; then
@@ -60,3 +63,5 @@ fi
 
 # Perform cleanup of unused commit repos.
 pre-commit gc
+
+exit $EXIT_CODE
